# tasks/alertnamager.yaml
- name: create folder {{ victoriametrics_container_name }}
  ansible.builtin.file:
    path: "{{ alertmanager_dir }}"
    group: "{{ username }}"
    owner: "{{ username }}"
    state: directory

- name: copy template alertmanager to {{ alertmanager_dir }}
  ansible.builtin.template:
    src: templates/alertmanager.yaml.j2
    dest: "{{ alertmanager_dir }}/alertmanager.yaml"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Create Alertmanager docker-compose file
  ansible.builtin.template:
    src: templates/alertmanager_compose.yaml.j2
    dest: "{{ alertmanager_dir }}/docker-compose.yaml"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Start Alertmanager container
  community.docker.docker_compose_v2:
    project_src: "{{ alertmanager_dir }}"
    state: present
