- name: create folder {{ victoriametrics_container_name }}
  ansible.builtin.file:
    path: "{{ victoriametrics_dir }}"
    group: "{{ username }}"
    owner: "{{ username }}"
    state: directory

- name: Create additional scrape configs directory
  ansible.builtin.file:
    path: "{{ additional_scrape_configs_dir }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0755'

- name: copy template scrape config to {{ victoriametrics_dir }}
  ansible.builtin.template:
    src: templates/scrape.yaml.j2
    dest: "{{ victoriametrics_dir }}/scrape.yaml"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Create Victoriametrics docker-compose file
  ansible.builtin.template:
    src: templates/victoriametrics_compose.yaml.j2
    dest: "{{ victoriametrics_dir }}/docker-compose.yaml"
    owner: "{{ username }}"
    group: "{{ username }}" 

- name: Start Victoriametrics container
  community.docker.docker_compose_v2:
    project_src: "{{ victoriametrics_dir }}"
    state: present