# tasks.vmalert.yaml
- name: create project {{ vmalert_container_name }}
  ansible.builtin.file:
    path: "{{ vmalert_dir }}"
    group: "{{ username }}"
    owner: "{{ username }}"
    state: directory

- name: create folder rules
  ansible.builtin.file:
    path: "{{ vmalert_rules_folder }}"
    group: "{{ username }}"
    owner: "{{ username }}"
    state: directory

- name: Copy rules
  ansible.builtin.copy:
    src: files/rules/
    dest: "{{ vmalert_rules_folder }}"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Create Vmalert docker-compose file
  ansible.builtin.template:
    src: templates/vmalert_compose.yaml.j2
    dest: "{{ vmalert_dir }}/docker-compose.yaml"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Start Vmalert container
  community.docker.docker_compose_v2:
    project_src: "{{ vmalert_dir }}"
    state: present
