# default/main.yaml
# network name used in docker-compose (can be overridden)
docker_network_name: "monitoring_network"

# victoriametrics
victoriametrics_enable: true
victoriametrics_version: v1.118.0
victoriametrics_container_name: victoriametrics
victoriametrics_repo: victoriametrics/victoria-metrics
victoriametrics_port: 8428
victoriametrics_url: vm.home.local
default_metrics_path: metrics
scrape_interval: 10s
scrape_file: scrape.yaml
scrape_folder: /etc/prometheus
additional_scrape_configs_dir: "{{ victoriametrics_dir }}/jobs"
victoriametrics_data: vmstorage
victoriametrics_image: "{{ victoriametrics_repo }}:{{ victoriametrics_version }}"

# vmalert config
vmalert_enable: true
vmalert_container_name: vmalert
vmalert_repo: victoriametrics/vmalert
vmalert_rules_folder: "{{vmalert_dir}}/rules"
vmalert_image: "{{ vmalert_repo }}:{{ vmalert_version }}"
vmalert_url: vmalert.home.local
vmalert_version: v1.118.0
vmalert_port: 8880

# alertmanager config
alertmanager_enable: true
alertmanager_image: "{{ alertmanager_repo }}:{{ alertmanager_version }}"
alertmanager_container_name: alertmanager
alertmanager_repo:  prom/alertmanager
alertmanager_version: v0.28.0
alertmanager_port: 9093
alertmanager_url: alertmanager.home.local

# grafana config
grafana_enable: true
grafana_container_name: grafana
grafana_repo:  grafana/grafana
grafana_version: 11.5.0
grafana_port: 3000
grafana_url: grafana.home.local
grafana_data: grafana
grafana_datasource_config: "{{ grafana_dir }}/datasources.yaml"
grafana_dashboard_config: "{{ grafana_dir }}/dashboards.yaml"
dashboards_folder: "{{ grafana_dir }}/dashboards"
grafana_dashboard_folder: /var/lib/grafana/dashboard
grafana_image: "{{ grafana_repo }}:{{ grafana_version }}"



