- name: reload victoriametrics
  ansible.builtin.uri:
    url: https://{{ victoriametrics_url }}/-/reload
    method: POST
    validate_certs: false
  register: reload_result
  retries: 10
  delay: 5
  until: reload_result.status == 200