# defaults/main.yaml
# Default variables for blackbox-exporter role
docker_network_name: ""

# Blackbox Exporter configuration
blackbox_exporter_docker_dir: "/home/{{ ansible_user }}/{{ blackbox_exporter_container_name }}"
blackbox_exporter_repository: "prom/blackbox-exporter"
blackbox_exporter_config_path: "/etc/blackbox-exporter/blackbox.yaml"
blackbox_exporter_version: "0.28.0"
blackbox_exporter_container_name: "blackbox_exporter"
blackbox_exporter_port: 9115
blackbox_exporter_restart_policy: "unless-stopped"
blackbox_exporter_url: blackbox.home.local
blackbox_tls_enabled: false
blackbox_exporter_basic_auth_enabled: false
blackbox_scrape_config_dir: ""
blackbox_exporter_basic_auth_username: "admin"
blackbox_exporter_basic_auth_password: "admin"
monitoring_server_groups: ""