hostname: blackbox
username: ubuntu
docker_network_name: blackbox
docker_version: "5:28.5.2-1"
packages:
- jq
- unzip

# traefik config
traefik_docker_dir: /home/{{ ansible_user }}/traefik
traefik_container_name: traefik
traefik_image: "traefik"
traefik_version: "v3.5"
acme_email: "vladoz77@yandex.ru"
traefik_acme_staging: false

# blackbox-exporter config
blackbox_exporter_url: blackbox.home-local.site
blackbox_exporter_basic_auth_enabled: true
blackbox_exporter_basic_auth_username: "admin"
blackbox_exporter_basic_auth_password_hash: "$$2y$$05$$.0V7zbZKg9HQILVOcK77m.ZtOizpRvKKp82oqx8cTKJfa6LFhy1HG" # admin:admin

# VictoriaMetrics config
victoriametrics_url: prometheus.home-local.site
grafana_url: grafana.home-local.site
alertmanager_url: alert.home-local.site
vmalert_url: vmalert.home-local.site
