hostname: blackbox
username: ubuntu
docker_network_name: blackbox
docker_version: "5:28.5.2-1"
packages:
- jq
- unzip

# traefik config
traefik_docker_dir: /home/{{ ansible_user }}/traefik
traefik_container_name: traefik
traefik_image: "traefik"
traefik_version: "v3.5"
acme_email: "vladoz77@yandex.ru"
traefik_acme_staging: false

# Blackbox config
blackbox_exporter_url: blackbox.home-local.site
blackbox_tls_enabled: true
blackbox_exporter_basic_auth_enabled: true
blackbox_exporter_basic_auth_username: "admin"
blackbox_exporter_basic_auth_password: "admin"
blackbox_scrape_config_dir: "/home/{{ansible_user}}/monitoring/victoriametrics/jobs"
monitoring_server_groups: monitoring-server
