# tasks/install.yaml
- name: Set username variables
  ansible.builtin.set_fact:
    username: "{{ username | default(ansible_user)  }}"
  changed_when: false

- name: Install python3-passlib
  ansible.builtin.apt:
    name:
      - python3-passlib
    state: present
    update_cache: true

- name: create folder {{ blackbox_exporter_container_name }}
  ansible.builtin.file:
    path: "{{ blackbox_exporter_docker_dir }}"
    group: "{{ username }}"
    owner: "{{ username }}"
    state: directory

- name: Copy template blackbox exporter config to {{ blackbox_exporter_docker_dir }}
  ansible.builtin.copy:
    src: "files/blackbox.yaml"
    dest: "{{ blackbox_exporter_docker_dir }}/blackbox.yaml"
    group: "{{ username }}"
    owner: "{{ username }}"

- name: Create password hash for traefic auth
  ansible.builtin.set_fact:
    blackbox_exporter_basic_auth_password_hash: "{{ blackbox_exporter_basic_auth_password | password_hash(hashtype='bcrypt') | regex_replace('\\$', '$$')}}"
  no_log: true
  changed_when: false
  when: blackbox_exporter_basic_auth_enabled

- name: Copy template docker-compose to {{ blackbox_exporter_docker_dir }}
  ansible.builtin.template:
    src: "templates/docker-compose.yaml.j2"
    dest: "{{ blackbox_exporter_docker_dir }}/docker-compose.yaml"
    group: "{{ username }}"
    owner: "{{ username }}"

- name: Start blackbox exporter
  community.docker.docker_compose_v2:
    project_src: "{{ blackbox_exporter_docker_dir }}"
    recreate: always
    state: present

- name: Copy scrape configuration
  ansible.builtin.template:
    src: templates/blackbox-scrape-config.yaml.j2
    dest: "{{ blackbox_scrape_config_dir }}/blackbox.yaml"
    group: "{{ username }}"
    owner: "{{ username }}"
  delegate_to: "{{ groups[monitoring_server_groups][0] }}"
  notify: reload victoriametrics
