name: Blackbox-monitoring CICD

on:
  workflow_dispatch:
    inputs:
      env:
        description: Target environment
        type: choice
        default: apply
        options:
        - stage
        - prod
      terraform_action:
        description: Choose terraform actions
        type: choice
        default: apply
        options:
        - apply
        - destroy
permissions:
  id-token: write


jobs:
  deploy_servers:
    runs-on: ubuntu-latest
    env:
      WORKING_DIR: "terraform"
      TF_ACTION: ${{ github.event.inputs.terraform_action }}
      ENV_NAME: ${{ github.event.inputs.env }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Config yandex provider
      run: |
        echo "Creating ~/.terraformrc for Yandex Cloud mirror"
        cat > ~/.terraformrc <<EOF
        provider_installation {
          network_mirror {
            url = "https://terraform-mirror.yandexcloud.net/"
            include = ["registry.terraform.io/*/*"]
          }
          direct {
             exclude = ["registry.terraform.io/*/*"]
          }
        }
        EOF

    - name: Generate IAM token
      id: get-iam-token
      uses: docker://ghcr.io/yc-actions/yc-iam-token-fed:1.0.0
      with:
        yc-sa-id: ${{ secrets.YC_SA_ID }}

    - name: Check terragrunt HCL
      uses: gruntwork-io/terragrunt-action@v3
      with:
          tg_version: '0.98.0'
          tf_path: /home/runner/.tfenv/bin/terraform
          tg_dir: ${{ env.WORKING_DIR }}/${{ env.ENV_NAME }}
          tg_command: 'hcl fmt --check --diff'

    - name: Init
      uses: gruntwork-io/terragrunt-action@v3
      with:
          tg_version: '0.98.0'
          tf_path: /home/runner/.tfenv/bin/terraform
          tg_dir: ${{ env.WORKING_DIR }}/${{ env.ENV_NAME }}
          tg_command: 'run --all init --terragrunt-non-interactive'
  
