name: Blackbox-monitoring CICD

on:
  workflow_dispatch:
    inputs:
      env:
        description: Target environment
        type: choice
        default: apply
        options:
        - stage
        - prod
      terraform_action:
        description: Choose terraform actions
        type: choice
        default: apply
        options:
        - apply
        - destroy
permissions:
  id-token: write

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      WORKING_DIR: "terraform"
      TF_ACTION: ${{ github.event.inputs.terraform_action }}
      ENV_NAME: ${{ github.event.inputs.env }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Check terragrunt HCL
      uses: gruntwork-io/terragrunt-action@v3
      with:
          tg_version: '1.9.8'
          tg_dir: ${{ env.WORKING_DIR }}/${{ env.ENV_NAME }}
          tg_command: 'hcl fmt --check --diff'
