name: Blackbox-monitoring CICD

on:
  workflow_dispatch:
    inputs:
      env:
        description: Target environment
        type: choice
        default: apply
        options:
        - stage
        - prod
      terraform_action:
        description: Choose terraform actions
        type: choice
        default: apply
        options:
        - apply
        - destroy
permissions:
  id-token: write


jobs:
  deploy_servers:
    runs-on: ubuntu-latest
    env:
      WORKING_DIR: "terraform"
      TF_ACTION: ${{ github.event.inputs.terraform_action }}
      ENV_NAME: ${{ github.event.inputs.env }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Config yandex provider
      run: |
        echo "Creating ~/.terraformrc for Yandex Cloud mirror"
        cat > ~/.terraformrc <<EOF
        provider_installation {
          network_mirror {
            url = "https://terraform-mirror.yandexcloud.net/"
            include = ["registry.terraform.io/*/*"]
          }
          direct {
             exclude = ["registry.terraform.io/*/*"]
          }
        }
        EOF

    - name: Generate IAM token
      id: get-iam-token
      uses: docker://ghcr.io/yc-actions/yc-iam-token-fed:1.0.0
      with:
        yc-sa-id: ${{ secrets.YC_SA_ID }}

    - name: Check terragrunt HCL
      uses: gruntwork-io/terragrunt-action@v3
      with:
          tg_dir: ${{ env.WORKING_DIR }}/${{ env.ENV_NAME }}
          tg_command: 'hcl fmt --check --diff'

    - name: Init
      uses: gruntwork-io/terragrunt-action@v3
      env:
        AWS_ACCESS_KEY_ID:     ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
      with:
          tg_dir: ${{ env.WORKING_DIR }}/${{ env.ENV_NAME }}
          tg_command: 'run --all init'

    - name: Apply
      if: env.TF_ACTION == 'apply'
      uses: gruntwork-io/terragrunt-action@v3
      env:
        TF_VAR_iam_token: ${{ steps.get-iam-token.outputs.token }}
        TF_VAR_cloud_id: ${{ secrets.TF_VAR_CLOUD_ID }}
        TF_VAR_folder_id: ${{ secrets.TF_VAR_FOLDER_ID }}
        TF_VAR_ssh_pub_key: ${{ secrets.SSH_PUB_KEY }}
        AWS_ACCESS_KEY_ID:     ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
      with:
          tg_dir: ${{ env.WORKING_DIR }}/${{ env.ENV_NAME }}
          tg_command: 'run --all apply --non-interactive'
  
    - name: Upload inventory file as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ansible-inventory
        path: ansible/inventories/${{env.ENV_NAME}}/inventory.ini

    - name: Destroy
      if: env.TF_ACTION == 'destroy'
      uses: gruntwork-io/terragrunt-action@v3
      env:
        TF_VAR_iam_token: ${{ steps.get-iam-token.outputs.token }}
        TF_VAR_cloud_id: ${{ secrets.TF_VAR_CLOUD_ID }}
        TF_VAR_folder_id: ${{ secrets.TF_VAR_FOLDER_ID }}
        TF_VAR_ssh_pub_key: ${{ secrets.SSH_PUB_KEY }}
        AWS_ACCESS_KEY_ID:     ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
      with:
          tg_dir: ${{ env.WORKING_DIR }}/${{ env.ENV_NAME }}
          tg_command: 'run --all destroy --non-interactive'

  ansible-provision:
    name: Provision  blackbox server
    needs: deploy_servers
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.terraform_action == 'apply' }}
    env:
      ENV_NAME: ${{ github.event.inputs.env }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download inventory artifact
      uses: actions/download-artifact@v4
      with:
        name: ansible-inventory
        path: ansible/inventories/${{env.ENV_NAME}}

    - name:  run playbook
      uses: dawidd6/action-ansible-playbook@v6
      with:
        playbook: ansible/blackbox-${{env.ENV_NAME}}.yaml
        key: ${{ secrets.SSH_PRIV_KEY }}
        options: |
         --inventory inventories/${{env.ENV_NAME}}/inventory.ini
         --ssh-extra-args "-o StrictHostKeyChecking=no"
         --extra-vars "aws_access_key=${{ secrets.ACME_AWS_ACCESS_KEY }} aws_secret_key=${{ secrets.ACME_AWS_SECRET }}"
         -u ubuntu